#!/bin/sh

make menuselect.makeopts
menuselect/menuselect --enable chan_ooh323 --enable format_mp3 \
                      --enable CORE-SOUNDS-EN-WAV --enable CORE-SOUNDS-EN-ULAW \
                      --enable CORE-SOUNDS-EN-ALAW --enable CORE-SOUNDS-EN-G729 \
                      --enable CORE-SOUNDS-EN-G722 --enable CORE-SOUNDS-EN-ULAW \
                      --enable CORE-SOUNDS-EN-ALAW --enable CORE-SOUNDS-EN-GSM
make
make install
make samples
make config
